from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FileArtifact(BaseModel):
    """生成・修正されたファイル単体"""

    model_config = ConfigDict(extra="forbid")
    path: str = Field(..., description="ファイルパス (例: dev_documents/CYCLE01/SPEC.md)")
    content: str = Field(..., description="ファイルの内容")
    language: str = Field("markdown", description="言語 (python, markdown, etc.)")


class CyclePlan(BaseModel):
    """計画フェーズの成果物一式"""

    model_config = ConfigDict(extra="forbid")
    spec_file: FileArtifact
    schema_file: FileArtifact
    uat_file: FileArtifact
    thought_process: str = Field(..., description="なぜこの設計にしたかの思考プロセス")


class AuditResult(BaseModel):
    """監査結果"""

    model_config = ConfigDict(extra="forbid")
    # Mapping 'approved' status to boolean is_approved
    status: str | None = None # Added to support mapping from LLMReviewer status string
    is_approved: bool = False
    reason: str | None = None
    feedback: str | None = None
    critical_issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


class UatAnalysis(BaseModel):
    """UAT実行結果の分析"""

    model_config = ConfigDict(extra="forbid")
    verdict: Literal["PASS", "FAIL"]
    summary: str
    behavior_analysis: str


class FileCreate(BaseModel):
    """New file creation"""

    model_config = ConfigDict(extra="forbid")
    operation: Literal["create"] = "create"
    path: str = Field(..., description="Path to the file to create")
    content: str = Field(..., description="Full content of the new file")


class FilePatch(BaseModel):
    """Existing file modification via patch"""

    model_config = ConfigDict(extra="forbid")
    operation: Literal["patch"] = "patch"
    path: str = Field(..., description="Path to the file to modify")
    search_block: str = Field(
        ...,
        description="Exact block of code to search for (must match original file exactly)",
    )
    replace_block: str = Field(
        ..., description="New block of code to replace the search block with"
    )


FileOperation = FileCreate | FilePatch


# --- Spec Structuring Models ---


class Feature(BaseModel):
    name: str
    description: str
    priority: Literal["High", "Medium", "Low"]
    acceptance_criteria: list[str]


class TechnicalConstraint(BaseModel):
    category: str
    description: str


class StructuredSpec(BaseModel):
    """Structured representation of ALL_SPEC.md"""

    project_name: str
    version: str = "1.0.0"
    overview: str = Field(..., description="Executive summary of the project")
    goals: list[str] = Field(..., description="Primary business/learning goals")
    architecture_overview: str = Field(..., description="High-level system design")
    features: list[Feature] = Field(..., description="Initial backlog of features")
    constraints: list[TechnicalConstraint] = Field(default_factory=list)
    terminology: dict[str, str] = Field(default_factory=dict, description="Domain glossary")


# --- System Architecture Models ---


class SystemArchitecture(BaseModel):
    """
    High-level System Architecture Design.
    Generated by Structurer Agent from raw requirements.
    """

    model_config = ConfigDict(extra="forbid")

    project_name: str = Field(..., description="Name of the project")
    background: str = Field(..., description="Project background and context")
    core_philosophy: str = Field(
        ..., description="Core design philosophy (e.g., minimalist, robust, rapid)"
    )
    user_stories: list[str] = Field(..., description="High-level user stories")
    system_design: str = Field(..., description="Overall system design and architecture pattern")
    module_structure: str = Field(
        ..., description="Breakdown of key modules and responsibilities (hierarchical or list)"
    )
    tech_stack: list[str] = Field(..., description="List of technologies and libraries to be used")
    implementation_roadmap: list[str] = Field(..., description="Step-by-step implementation phases")


class PlanAuditResult(BaseModel):
    """Result of AI-on-AI Plan Audit"""

    model_config = ConfigDict(extra="forbid")
    status: Literal["APPROVED", "REJECTED"]
    reason: str
    feedback: str | None = Field(default="", description="Mandatory if REJECTED")
