#!/usr/bin/env python3
import argparse
import json
import time
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Mock Jules CLI")
    parser.add_argument("command", choices=["chat"], help="Command to run")
    parser.add_argument("--session", required=True, help="Session ID")
    parser.add_argument("--file", action="append", help="Context files")
    parser.add_argument("prompt", nargs="?", help="The prompt message")

    args = parser.parse_args()

    print(f"[MockJules] Starting session {args.session}...")
    print(f"[MockJules] Processing files: {args.file}")

    # Simulate processing time
    time.sleep(2)

    # Determine output based on context (heuristic)
    # If ARCHITECT_INSTRUCTION.md is in files -> Architect Session
    # If CODER_INSTRUCTION.md is in files -> Coder Session

    is_architect = False
    is_coder = False
    cycle_id = "01" # Default

    if args.file:
        for f in args.file:
            if "ARCHITECT_INSTRUCTION.md" in f:
                is_architect = True
            if "CODER_INSTRUCTION.md" in f:
                is_coder = True
            # Try to extract cycle from file path if possible, e.g. CYCLE01/SPEC.md
            if "CYCLE" in f:
                parts = f.split("CYCLE")
                if len(parts) > 1:
                    cycle_id = parts[1][:2]

    # Create dummy outputs
    if is_architect:
        print("[MockJules] Detected Architect Session")
        # 1. Create SYSTEM_ARCHITECTURE.md
        arch_path = Path("dev_documents/SYSTEM_ARCHITECTURE.md")
        arch_path.parent.mkdir(parents=True, exist_ok=True)
        arch_path.write_text(
            "# Mock System Architecture\n\nGenerated by Mock Jules.", encoding="utf-8"
        )

        # 2. Create CYCLE01/SPEC.md and UAT.md
        cycle_dir = Path(f"dev_documents/CYCLE{cycle_id}")
        cycle_dir.mkdir(parents=True, exist_ok=True)
        (cycle_dir / "SPEC.md").write_text(
            "# Mock SPEC\n\nGenerated by Mock Jules.", encoding="utf-8"
        )
        (cycle_dir / "UAT.md").write_text(
            "# Mock UAT\n\nGenerated by Mock Jules.", encoding="utf-8"
        )

        # 3. Write Completion Signal
        signal_path = Path("dev_documents/plan_status.json")
        signal_data = {"status": "completed", "cycles": [cycle_id]}
        signal_path.write_text(json.dumps(signal_data, indent=2), encoding="utf-8")
        print(f"[MockJules] Wrote signal to {signal_path}")

    elif is_coder:
        print(f"[MockJules] Detected Coder Session for Cycle {cycle_id}")
        # 1. Write Completion Signal
        signal_path = Path(f"dev_documents/CYCLE{cycle_id}/session_report.json")
        signal_path.parent.mkdir(parents=True, exist_ok=True)
        signal_data = {"status": "implemented", "test_result": "passed"}
        signal_path.write_text(json.dumps(signal_data, indent=2), encoding="utf-8")
        print(f"[MockJules] Wrote signal to {signal_path}")

    else:
        print("[MockJules] Unknown session type. No signal written.")

if __name__ == "__main__":
    main()
