# dev_src/ac_cdd_core/interfaces.py
from typing import Any, Protocol, runtime_checkable

from .domain_models import CycleManifest
from .state import CycleState


@runtime_checkable
class IGraphNodes(Protocol):
    async def architect_session_node(self, state: CycleState) -> dict[str, Any]: ...
    async def coder_session_node(self, state: CycleState) -> dict[str, Any]: ...
    async def auditor_node(self, state: CycleState) -> dict[str, Any]: ...
    async def committee_manager_node(self, state: CycleState) -> dict[str, Any]: ...
    async def uat_evaluate_node(self, state: CycleState) -> dict[str, Any]: ...
    def check_coder_outcome(self, state: CycleState) -> str: ...
    def check_audit_outcome(self, state: CycleState) -> str: ...
    def route_committee(self, state: CycleState) -> str: ...


@runtime_checkable
class IJulesClient(Protocol):
    async def run_session(self, **kwargs: Any) -> dict[str, Any]: ...
    async def wait_for_completion(self, session_id: str) -> dict[str, Any]: ...
    async def send_message_to_session(self, session_id: str, message: str) -> None: ...


@runtime_checkable
class ISessionManager(Protocol):
    async def get_cycle(self, cycle_id: str) -> CycleManifest | None: ...
    async def update_cycle_state(self, cycle_id: str, **kwargs: Any) -> None: ...


@runtime_checkable
class IWorkflowOrchestrator(Protocol):
    async def run_gen_cycles(self, cycles: int, project_session_id: str | None) -> None: ...
    async def run_cycle(
        self,
        cycle_id: str,
        resume: bool,
        auto: bool,
        start_iter: int,
        project_session_id: str | None,
    ) -> None: ...
    async def start_session(self, prompt: str, audit_mode: bool, max_retries: int) -> None: ...
    async def finalize_session(self, project_session_id: str | None) -> None: ...
