from typing import Any, Protocol

from ac_cdd_core.state import CycleState


class IGraphNodes(Protocol):
    async def architect_session_node(self, state: CycleState) -> dict[str, Any]: ...
    async def coder_session_node(self, state: CycleState) -> dict[str, Any]: ...
    async def auditor_node(self, state: CycleState) -> dict[str, Any]: ...
    async def committee_manager_node(self, state: CycleState) -> dict[str, Any]: ...
    async def uat_evaluate_node(self, state: CycleState) -> dict[str, Any]: ...
    def check_coder_outcome(self, state: CycleState) -> str: ...
    def route_committee(self, state: CycleState) -> str: ...

    # Define as a variable, not a property, to avoid runtime setter conflicts
    llm_reviewer: Any


class IWorkflowOrchestrator(Protocol):
    async def run_gen_cycles(self, cycles: int, project_session_id: str | None) -> None: ...
    async def run_cycle(self, cycle_id: str, resume: bool, auto: bool, start_iter: int, project_session_id: str | None) -> None: ...
    async def start_session(self, prompt: str, audit_mode: bool, max_retries: int) -> None: ...
    async def finalize_session(self, project_session_id: str | None) -> None: ...
